version: '3.8'

services:
  jupyter-gpu:
    build: .
    container_name: jupyter-gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    volumes:
      - .:/workspace
    command: start-notebook.sh --NotebookApp.token=''
